"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { MacFastHeader } from "@/components/ui/custom/macfast-header";
import { Button } from "@/components/ui/button";
import { ChevronsRight, MinusCircleIcon, PlusCircleIcon } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useAuthFetch } from "@/hooks/useFetchWithAuth";
import { QuestionPage } from "@/components/ui/custom/question-page";
import { Textarea } from "@/components/ui/textarea";
import { isEqual } from "lodash";
import ErrorMessage from "@/components/ui/custom/error-message";
import { getQuestionByPublicId } from "@/lib/api";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";

export default function QuestionEditPage() {
  const params = useParams();
  const router = useRouter();
  const authFetch = useAuthFetch();
  const courseCode = decodeURIComponent(params.courseCode as string);
  const questionId = decodeURIComponent(params.questionId as string);
  const [question, setQuestion] = useState<Question | null>(null);
  const [questionCopy, setQuestionCopy] = useState<Question | null>(null);
  const [isQuestionLoading, setIsQuestionLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [answerIndex, setAnswerIndex] = useState<number>(0);

  const hasChanges = () => {
    return !isEqual(question, questionCopy);
  };

  const handleCancel = () => {
    setQuestion(questionCopy);
    router.back();
  };

  const deleteQuestionOption = (optionIndex: number) => {
    setQuestion((prev) => {
      if (!prev || !prev.options) return prev;
      const updatedOptions = prev.options.filter(
        (_, index) => index !== optionIndex,
      );
      return { ...prev, options: updatedOptions };
    });
    if (!question || !question.options) return;
    if (answerIndex === optionIndex) {
      if (answerIndex >= question.options.length - 1) {
        setAnswerIndex(question.options.length - 2);
      } else {
        setAnswerIndex(answerIndex);
      }
    }
  };

  const addQuestionOption = () => {
    const newOption: QuestionOption = {
      public_id: "", // This should ideally be generated by the backend
      content: "",
      is_answer: false,
      selection_frequency: 0,
    };
    setQuestion((prev) => {
      if (!prev) return prev;
      const updatedOptions = prev.options
        ? [...prev.options, newOption]
        : [newOption];
      return { ...prev, options: updatedOptions };
    });
  };

  const handleOptionContentChange = (
    e: React.ChangeEvent<HTMLTextAreaElement>,
    optionIndex: number,
  ) => {
    if (!question || !question.options) return;

    setQuestion((prev) => {
      if (!prev) return prev;
      const updatedOptions = prev.options;
      updatedOptions[optionIndex] = {
        ...updatedOptions[optionIndex],
        content: e.target.value,
      };
      return { ...prev, options: updatedOptions };
    });
  };

  useEffect(() => {
    setIsQuestionLoading(true);
    getQuestionByPublicId(questionId, authFetch)
      .then((data) => {
        setQuestion(data);
        setQuestionCopy(structuredClone(data));
        if (!data.options) {
          setError("Question options are missing");
          return;
        }
        const correctOption = data.options.findIndex(
          (option) => option.is_answer,
        );
        setAnswerIndex(correctOption !== -1 ? correctOption : 0);
      })
      .catch((error) => {
        setError(error.message);
      })
      .finally(() => {
        setIsQuestionLoading(false);
      });
  }, [questionId]);

  if (!isQuestionLoading && question && !question.options) {
    return (
      <QuestionPage>
        <QuestionPage.Header>
          <MacFastHeader />
        </QuestionPage.Header>
        <QuestionPage.Title>
          <h1>{question.course}</h1>#<h1>{questionId}</h1>
        </QuestionPage.Title>
        <QuestionPage.Content>
          <div>
            <ErrorMessage message="Question data is malformed." />
          </div>
        </QuestionPage.Content>
      </QuestionPage>
    );
  }

  return (
    <QuestionPage>
      <QuestionPage.Header>
        <MacFastHeader />
      </QuestionPage.Header>
      <QuestionPage.Title>
        <h1>{courseCode}</h1>
        <ChevronsRight />
        <h1>
          {question?.unit} - {question?.subtopic}
        </h1>
      </QuestionPage.Title>

      <QuestionPage.Content>
        <QuestionPage.QuestionBody
          error={error || ""}
          isLoading={isQuestionLoading}
        >
          <Textarea
            placeholder="Question content..."
            className="border p-4 rounded-lg shadow-md bg-background h-40"
            label={"Question Content"}
            value={question?.content || ""}
            onChange={(e) =>
              setQuestion((prev) =>
                prev != null ? { ...prev, content: e.target.value } : null,
              )
            }
          />
          <QuestionPage.Options isLoading={isQuestionLoading}>
            <RadioGroup
              value={answerIndex.toString()}
              onValueChange={(val) => setAnswerIndex(parseInt(val))}
            >
              {question?.options.map((option, index) => (
                <div key={index} className="flex items-center gap-2 w-full">
                  <RadioGroupItem
                    value={index.toString()}
                    className="cursor-pointer"
                    checked={answerIndex === index}
                  />
                  <div className="w-full">
                    <Textarea
                      placeholder="Option content..."
                      className={answerIndex === index ? " border-primary" : ""}
                      value={option.content}
                      onChange={(e) => handleOptionContentChange(e, index)}
                    />
                  </div>
                  <MinusCircleIcon
                    className="cursor-pointer text-primary w-5"
                    onClick={() => deleteQuestionOption(index)}
                  />
                </div>
              ))}
            </RadioGroup>
            <div className="flex items-center gap-2 w-full justify-center">
              <Button variant="tertiary" onClick={addQuestionOption}>
                Add option
                <PlusCircleIcon

                // onClick={addQuestionOption}
                />
              </Button>
            </div>
          </QuestionPage.Options>
        </QuestionPage.QuestionBody>
        <QuestionPage.Answer isLoading={isQuestionLoading}>
          <QuestionPage.AnswerTitle>
            <p
              className="font-poppins text-2xl"
              dangerouslySetInnerHTML={{
                __html: question?.options[answerIndex]?.content || "",
              }}
            ></p>
          </QuestionPage.AnswerTitle>
          <QuestionPage.AnswerBody>
            <Textarea
              placeholder="Answer explanation..."
              className="border p-4 rounded-lg shadow-md bg-background h-40"
              value={question?.answer_explanation || ""}
              onChange={(e) => {
                setQuestion((prev) =>
                  prev != null
                    ? { ...prev, answer_explanation: e.target.value }
                    : null,
                );
              }}
            />
          </QuestionPage.AnswerBody>
        </QuestionPage.Answer>
      </QuestionPage.Content>

      <QuestionPage.Actions>
        <div className="ml-auto flex gap-2">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="secondary" disabled={!hasChanges()}>
                Cancel
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogTitle>Discard changes?</AlertDialogTitle>
              <AlertDialogDescription>
                You have unsaved changes. Are you sure you want to discard them?
                This cannot be undone.
              </AlertDialogDescription>
              <AlertDialogAction>Keep Editing</AlertDialogAction>
              <AlertDialogCancel onClick={handleCancel}>
                Discard Changes
              </AlertDialogCancel>
            </AlertDialogContent>
          </AlertDialog>

          <Button
            disabled={!hasChanges()}
            onClick={() => alert("Save functionality not implemented yet")}
          >
            Save
          </Button>
        </div>
      </QuestionPage.Actions>
    </QuestionPage>
  );
}
