"use client";

import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";

// AI generated by Gemini

export interface XpCircleProps {
  level: number;
  percentage: number;
  isLoading: boolean;
  className?: string;
}

export const XpCircle = ({
  level,
  percentage,
  isLoading,
  className,
}: XpCircleProps) => {
  if (isLoading) {
    return <Skeleton className={cn("rounded-full bg-background", className)} />;
  }

  // Define SVG constants
  const size = 96; // 6rem / w-24
  const strokeWidth = 8;
  const center = size / 2;
  const radius = center - strokeWidth / 2;
  const circumference = 2 * Math.PI * radius;

  // Ensure percentage is bounded (0-100)
  const safePercentage = Math.max(0, Math.min(100, percentage));

  // Calculate dash offset (remaining percentage)
  const offset = circumference * (1 - safePercentage / 100);

  return (
    <div
      className={cn("relative", className)}
      style={{ width: size, height: size }}
    >
      <svg
        className="block -rotate-90" // Rotate so the progress starts at 12 o'clock
        viewBox={`0 0 ${size} ${size}`}
        width={size}
        height={size}
      >
        <defs>
          <linearGradient id="xp-gradient" x1="100%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="#800000" /> {/* Maroon */}
            <stop offset="50%" stopColor="#f97316" />{" "}
            {/* Tailwind orange-500 */}
            <stop offset="100%" stopColor="#ffd700" /> {/* Gold */}
          </linearGradient>
        </defs>

        {/* Background Gray Ring */}
        <circle
          className="stroke-muted-foreground fill-none"
          cx={center}
          cy={center}
          r={radius}
          strokeWidth={strokeWidth}
        />

        {/* Progress Ring */}
        <circle
          className="fill-none transition-all duration-1000 ease-out"
          stroke="url(#xp-gradient)"
          cx={center}
          cy={center}
          r={radius}
          strokeWidth={strokeWidth}
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          strokeLinecap="round"
        />
      </svg>

      {/* Level Number in the center */}
      <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
        <span className="text-4xl font-extrabold leading-none text-foreground">
          {level}
        </span>
        <span className="text-xs font-semibold uppercase tracking-widest text-muted-foreground -mt-1">
          lvl
        </span>
      </div>
    </div>
  );
};
